function ppm_blender_execute(ppm)
%ppm_blender_execute - Send the parameter values to be modified to Blender 
%                      and update the parametric pinna model (PPM) as specified 
%                      in the PPM structure array.
%
% Usage: 
%   ppm = ppm_blender_execute(ppm,varargin)
%
% Input parameters:
%
%   Required
%     ppm      : PPM structure array, initialized as per ppm_initialize(), 
%                with parameters set via ppm_set_values(). 
%
% Note: This function is called within ppm_set_values().

% #Author: Florian Pausch (2022)

%% Parse input arguments
% convert 1 and 0 to TRUE and FALSE, respectively (for Python scripts)
parsePool = [ppm.modify.mesh, ppm.modify.remesh, ppm.modify.image, ppm.modify.set_cam,...
    ppm.modify.depth];
parsePoolString = {'TRUE','FALSE'};
parsedStrings = parsePoolString((parsePool==0)+1);

%% Execute Blender via Python scripts
switch ppm.ini.verbose_level
    
    case 0
        args = [ppm.ini.path.blender_exe, ' ', ppm.ini.blender_file...
            ' -b -P ' fullfile(ppm.ini.path.python,'set_values_and_export_mesh_v1_4_0.py'),' -- ', ...
            ppm.ini.path.result, ' ',...
            parsedStrings{1}, ' ',...
            parsedStrings{2}, ' ',...
            parsedStrings{3},' ',...
            num2str(ppm.modify.image_res),' ',...
            num2str(ppm.modify.image_col_dep),' ',...
            num2str(ppm.modify.image_comp),' ',...
            parsedStrings{4},' ',...
            parsedStrings{5},' ',...
            num2str(ppm.modify.depth_col_dep_exr),' ',...
            num2str(ppm.modify.depth_comp_exr),' ',...
            ppm.modify.depth_codec_exr,' ',...
            num2str(ppm.modify.depth_col_dep_png),' ',...
            num2str(ppm.modify.depth_comp_png),' ',...
            num2str(ppm.modify.depth_nearest),' ',...
            num2str(ppm.modify.depth_farthest),...
            ' -a > nul 2>&1', ];
        
        stat = system(args);
        if stat
            error('Mesh manipulations were not successful. Aborted.')
        else
            if ppm.ini.verbose_level>0
                disp([mfilename,': Mesh manipulations were successful.'])
            end
        end
        
    case 1
        disp([mfilename,': Sending modified parameter values to blender. Manipulating mesh...'])
        args = [ppm.ini.path.blender_exe, ' ', ppm.ini.blender_file...
            ' -b -P ' fullfile(ppm.ini.path.python,'set_values_and_export_mesh_v1_4_0.py'),' -- ', ...
            ppm.ini.path.result, ' ',...
            parsedStrings{1}, ' ',...
            parsedStrings{2}, ' ',...
            parsedStrings{3},' ',...
            num2str(ppm.modify.image_res),' ',...
            num2str(ppm.modify.image_col_dep),' ',...
            num2str(ppm.modify.image_comp),' ',...
            parsedStrings{4},' ',...
            parsedStrings{5},' ',...
            num2str(ppm.modify.depth_col_dep_exr),' ',...
            num2str(ppm.modify.depth_comp_exr),' ',...
            ppm.modify.depth_codec_exr,' ',...
            num2str(ppm.modify.depth_col_dep_png),' ',...
            num2str(ppm.modify.depth_comp_png),' ',...
            num2str(ppm.modify.depth_nearest),' ',...
            num2str(ppm.modify.depth_farthest),...
            ' -a > nul 2>&1'];
        
        stat = system(args);
        if stat
            error('Mesh manipulations were not successful. Aborted.')
        else
            if ppm.ini.verbose_level>0
                disp([mfilename,': Mesh manipulations were successful.'])
            end
        end
        
        
    case 2
        disp([mfilename,': Sending modified parameter values to blender. Manipulating mesh...'])
        args = [ppm.ini.path.blender_exe, ' ', ppm.ini.blender_file...
            ' -b -P ' fullfile(ppm.ini.path.python,'set_values_and_export_mesh_v1_4_0.py'),' -- ', ...
            ppm.ini.path.result, ' ',...
            parsedStrings{1}, ' ',...
            parsedStrings{2}, ' ',...
            parsedStrings{3},' ',...
            num2str(ppm.modify.image_res),' ',...
            num2str(ppm.modify.image_col_dep),' ',...
            num2str(ppm.modify.image_comp),' ',...
            parsedStrings{4},' ',...
            parsedStrings{5},' ',...
            num2str(ppm.modify.depth_col_dep_exr),' ',...
            num2str(ppm.modify.depth_comp_exr),' ',...
            ppm.modify.depth_codec_exr,' ',...
            num2str(ppm.modify.depth_col_dep_png),' ',...
            num2str(ppm.modify.depth_comp_png),' ',...
            num2str(ppm.modify.depth_nearest),' ',...
            num2str(ppm.modify.depth_farthest),...
            ' '];
        
        stat = system(args);
        if stat
            error('Mesh manipulation were not successful. Aborted.')
        else
            if ppm.ini.verbose_level>0
                disp([mfilename,': Mesh manipulations were successful.'])
            end
        end
        
end
   
% delete(fullfile(ppm.ini.path.result,'blender_render.log'));