%% MATLAB script to demonstrate the functionality of the interface to the 
%  parametric pinna model (PPM), including bi-directional communication with 
%  Blender via Python API
%
% The PPM was developed at the Acoustics Research Institute (ARI) of the 
% Austrian Academy of Sciences, Vienna, Austria [1-4]
%
% Dependencies:
% MATLAB (tested with version 9.11.0.1769968, R2021b) 
% MATLAB Computer Vision Toolbox (tested with version 10.1, R2021b)
% MATLAB class `quaternion` (version 1.8.0.0 by Mark Tincknell, downloaded 
%                            on the fly from MATLAB File Exchange)
% Python (tested with version 3.10.5, Jun 6, 2022)
% Blender (tested with version: 3.1.2, branch: master, 
%          commit date: 2022-03-31 17:40, hash: cc66d1020c3b, type: release
%          build date: 2022-03-31, 23:39:57)
% Blender model ARI_PPM_v1 (armature and object definitions)
%
% Related functions : ppm_initialize, ppm_get_values, ppm_set_values, 
%                     ppm_evaluate, ppm_test
%
% [1] Pollack K.; Majdak P.; Brinkmann F.; Kreuzer W. (2021) Von Fotos zu 
%     personalisierter räumlicher Audiowiedergabe. e & i Elektrotechnik und 
%     Informationstechnik.
% [2] Pollack K.; Majdak P.; Furtado H. (2021) Evaluation of Pinna Point 
%     Cloud Alignment by Means of Non-Rigid registration Algorithms. Audio 
%     Engineering Society (AES) 150th convention.
% [3] Pollack K.; Majdak P. (2021) Evaluation of a Parametric Pinna Model 
%     for the Calculation of Head-Related Transfer Functions. Immersive and 
%     3D Audio (I3DA) conference.
% [4] Pollack K.; Majdak P.; Furtado H. (2020) A Parametric Pinna Model for 
%     the Calculations of Head-Related Transfer Functions. Proceedings of 
%     Forum Acusticum 2020, Lyon. S. 1357-1360.

% Versions and contributors:
% 0.8 and above: Florian Pausch (2022)
% 0.7 and below: Mantas Tamulionis (2021)
%
% Current release version: 1.5.0

clear; close all; clc

% Change a single or multiple PPM-parameter values
type_ppm_input = 'single'; % {'single','multi'}

%% Initialize PPM
name_blender_file = 'PPM_modified_v1.blend';

ppm = ppm_initialize(...
    'path_blender_file',fullfile(pwd,'result'),...
    'name_blender_file',name_blender_file,...
    'verbose_level',1,...
    'auto_delete',true);

%% Get parameter values from specified Blender file and export mesh
[ppm,val] = ppm_get_values(ppm,...
    'type','Location',...
    'name','Size-Bendy',...
    'axis',[],...
    'pc',true,...
    'mesh',false);

% Display the selected parameter subset
if ppm.ini.verbose_level>0
    disp(val)
end

%% Set and apply parameter value to specified Blender file, export mesh, 
% and optionally render image (including depth data)

% Type 'ppm.parameters' to get a list of all parameters
% Type 'help ppm_set_values' to obtain further information 

switch type_ppm_input

    case 'single'

        % Single-parameter input
        ppm = ppm_set_values(ppm,...
            'type','Rotation',...
            'name','Size-Bendy',...
            'axis','X',...
            'val',2.1,...
            'range',4,...
            'itr',1,...
            'instruction_mode','abs', ...
            'rotation_mode','quaternion',...
            'image',true,...
            'image_res',512,...
            'image_col_dep',16,...
            'image_comp',15,...
            'pc',true,...
            'mesh',true,...
            'remesh',false,...
            'set_cam',false,...
            'cam_rot',[45, 0, 180],...
            'cam_loc',[-90, 200, 0],...
            'cam_loc_ref',[-10, 100, 5],... % e.g. [-10, 100, 5]
            'depth',true,...
            'depth_col_dep_exr',16,...
            'depth_comp_exr',15,...
            'depth_codec_exr','ZIP', ...
            'depth_col_dep_png',16,...
            'depth_comp_png',15,...
            'depth_nearest',[],...
            'depth_farthest',0);

    case 'multi'

        % Multiple-parameter input (and further optional parameters in ppm_set_values())
        selection_cell = [8:10, 155:157, 164:166];
%         selection_cell = [1:3,5:10,12:14,33:35,40:42];
%         selection_cell = 1:size(ppm.parameters,1);

        type_cell = ppm.parameters(selection_cell,1);
        name_cell = ppm.parameters(selection_cell,2);
        axis_cell = ppm.parameters(selection_cell,3);
        val_cell = cellfun(@(x) x-0.07, ppm.parameters(selection_cell,4),'UniformOutput',0);

        ppm = ppm_set_values(ppm,...
            'type',type_cell,...
            'name',name_cell,...
            'axis',axis_cell,...
            'val',val_cell,...
            'range',4,...
            'itr',5,...
            'instruction_mode','abs', ...
            'rotation_mode','quaternion',...
            'image',true,...
            'image_res',1024,...
            'image_col_dep',16,...
            'image_comp',15,...
            'pc',true,...
            'mesh',true,...
            'remesh',false,...
            'set_cam',false,...
            'cam_rot',[45, 0, 180],...
            'cam_loc',[-90, 200, 0],...
            'cam_loc_ref',[-10, 100, 5],... % e.g. [-10, 100, 5]
            'depth',true,...
            'depth_col_dep_exr',16,...
            'depth_comp_exr',15,...
            'depth_codec_exr','ZIP', ...
            'depth_col_dep_png',16,...
            'depth_comp_png',15,...
            'depth_nearest',[],...
            'depth_farthest',0);

end

%% Compare the resulting mesh to a specified target mesh
%  and evaluate its fit based on the Hausdorff distance, plot result
name_mesh_target = 'PPM_default_v1.ply';

ppm = ppm_evaluate(ppm,...
    'path_mesh_target',ppm.ini.path.data,...
    'name_mesh_target',name_mesh_target,...
    'caxis_min',0,...
    'caxis_max',5);
