[project]
name = "ppm"
description = "PPM - PPM Python Package"
version = "0.0.1"
authors = [
    { name = "Felix Perfler", email = "felix.perfler@oeaw.ac.at" },
    { name = "Florian Pausch", email = "florian.pausch@oeaw.ac.at"}
]
dependencies = [
    "bpy",
    "numpy",
    "opencv-python",
    "pyntcloud",
    "matplotlib"
]

[build-system]
requires = [ "setuptools", "cython", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp* cp36-* cp37-* *-musllinux*"
test-requires = ["pytest"]
test-command = "pytest --pyargs refnx.reflect.test.test_reflect"
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

# On an Linux Intel runner with qemu installed, build Intel and ARM wheels
[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"
archs = ["x86_64"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]