[project]
name = "ppm"
description = "PPM - PPM Python Package"
version = "0.0.1"
authors = [
    { name = "Felix Perfler", email = "felix.perfler@oeaw.ac.at" },
    { name = "Florian Pausch", email = "florian.pausch@oeaw.ac.at"}
]
dependencies = [
    "bpy",
    "numpy",
    "opencv-python",
    "pyntcloud",
    "matplotlib"
]

[tool.setuptools.package-data]
"ppm.resources" = ["*.blend", "*.csv"]

[tool.setuptools.packages.find]
where = ["ppm"]
