name: Make Blender Add-on release

on:
    release:
      types: [published]

jobs:
    deploy:
        if: startsWith(github.ref, 'refs/tags/Blender_Add-on')
        runs-on: ${{ matrix.os }}

        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
        - uses: actions/checkout@v1

        - name: Get release
          id: get_release
          uses: bruceadams/get-release@v1.3.2
          env:
            GITHUB_TOKEN: ${{ github.token }}
            
        - name: Compile
          run: |
            gcc -shared -c -fpic -o haus_46.so CLibrary/c_sum.c
            
        - name: Move Exe
          run: |
            mv haus_46.so Blender\ Add-on/haus_46.so

        - name: Make zip
          run: |
            zip -r 'Blender Add-on.zip' 'Blender Add-on'

        - name: Upload release asset
          uses: actions/upload-release-asset@v1.0.2
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: './Blender Add-on.zip'
            asset_name: 'Blender Add-on.zip'
            asset_content_type: 'application/zip'
